### ISSUE TITLE
Project Participants should append their names in the README.md file

### ISSUE THREAD

**Issue by CloudTechy** [Stevecmd/Tic-Tac-Triumph#4]
If you are contributing to the project, kindly include your name to the readme.md file and open a pull request to main branch.
@Xmaz2150 @Taha-Hakkou @ugoMusk @JOY-OKORO

**Comment by Stevecmd** [comment]
Members appended their names in the README on their respective branches, final merge will be done later...

**Comment by CloudTechy** [comment]
> Members appended their names in the README on their respective branches, final merge will be done later...

so why did you have to close it?

**Comment by Stevecmd** [comment]
People appended their names, check their branches... all that needs to be done is merging them

**Comment by CloudTechy** [comment]
ok cool, let's just keep it as a reminder until the merging process is completed
